import './style.css';

export { Table, Table as VelocityGrid } from './Table';
export { buildColumnMetrics, getViewportRange, hitTestColumn } from './core/layout';
export type {
  AxisSelectionConfig,
  RowSelectionConfig,
  TableRowNumberConfig,
  CellChange,
  TableCellContext,
  TableRef,
  TableRef as VelocityGridRef,
  CellChange as TableCellChange,
  ContextMenuEvent,
  ContextMenuEvent as TableContextMenuEvent,
  GridCellPosition,
  GridCellPosition as TableCellPosition,
  GridColumn,
  GridColumn as TableColumn,
  GridKey,
  GridKey as TableKey,
  GridSelection,
  GridSelection as TableEditingCell,
  GridSelectionTarget,
  GridSortState,
  GridSortState as TableSorter,
  SelectionMode,
  SelectedCellChange,
  SortDirection,
  TableContextMenu,
  TableContextMenu as VelocityGridContextMenu,
  TableCellSpan,
  TableCellSpan as VelocityGridCellSpan,
  TableContextMenuConfig,
  TableContextMenuConfig as VelocityGridContextMenuConfig,
  TableHighlightConfig,
  TableHighlightConfig as VelocityGridHighlightConfig,
  TableLayoutConfig,
  TableLayoutConfig as VelocityGridLayoutConfig,
  TableLabels,
  TableLabels as VelocityGridLabels,
  TableLocaleCode,
  TableLocaleCode as VelocityGridLocaleCode,
  TableLocaleConfig,
  TableLocaleConfig as VelocityGridLocaleConfig,
  TableProps,
  TableProps as VelocityGridProps,
  TableResolvedCellSpan,
  TableResolvedCellSpan as VelocityGridResolvedCellSpan,
  TableCellSpanRule,
  TableCellSpanRule as VelocityGridCellSpanRule,
  TableCellSpanRuleContext,
  TableCellSpanRuleContext as VelocityGridCellSpanRuleContext,
  TableCellSpans,
  TableCellSpans as VelocityGridCellSpans,
  TableSummaryConfig,
  TableSummaryConfig as VelocityGridSummaryConfig,
  TableTooltipConfig,
  TableTooltipConfig as VelocityGridTooltipConfig,
  TableVirtualizedConfig,
  TableVirtualizedConfig as VelocityGridVirtualizedConfig,
  ViewportRange,
  ViewportRange as TableViewportRange,
} from './types';

export type TableFilterValues = Record<string, string>;
