import './style.css';

export { Table, Table as VelocityGrid } from './Table';
export { buildColumnMetrics, getViewportRange, hitTestColumn } from './core/layout';
export type {
  AxisSelectionConfig,
  CellChange,
  CellChange as TableCellChange,
  ContextMenuEvent,
  ContextMenuEvent as TableContextMenuEvent,
  DeleteRowsEvent,
  DeleteRowsEvent as TableDeleteRowsEvent,
  GridCellPosition,
  GridCellPosition as TableCellPosition,
  GridColumn,
  GridColumn as TableColumn,
  GridKey,
  GridKey as TableKey,
  GridSelection,
  GridSelection as TableEditingCell,
  GridSortState,
  GridSortState as TableSorter,
  InsertRowsEvent,
  InsertRowsEvent as TableInsertRowsEvent,
  SelectionMode,
  SortDirection,
  TableContextMenu,
  TableContextMenu as VelocityGridContextMenu,
  TableCellSpan,
  TableCellSpan as VelocityGridCellSpan,
  TableContextMenuConfig,
  TableContextMenuConfig as VelocityGridContextMenuConfig,
  TableHighlightConfig,
  TableHighlightConfig as VelocityGridHighlightConfig,
  TableLabels,
  TableLabels as VelocityGridLabels,
  TableLocaleCode,
  TableLocaleCode as VelocityGridLocaleCode,
  TableLocaleConfig,
  TableLocaleConfig as VelocityGridLocaleConfig,
  TableProps,
  TableProps as VelocityGridProps,
  TableResolvedCellSpan,
  TableResolvedCellSpan as VelocityGridResolvedCellSpan,
  TableSummaryConfig,
  TableSummaryConfig as VelocityGridSummaryConfig,
  TableTooltipConfig,
  TableTooltipConfig as VelocityGridTooltipConfig,
  TableVirtualizedConfig,
  TableVirtualizedConfig as VelocityGridVirtualizedConfig,
  ViewportRange,
  ViewportRange as TableViewportRange,
} from './types';

export type TableFilterValues = Record<string, string>;
